services:
  db:
    restart: always
    ports:
      - 5433:5432
    image: postgres
    volumes:
      - ../data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    container_name: postgres_db

  app:
    build: .
    restart: always
    ports:
      - "8000:8000"
    image: app:hello-img
    container_name: hello-name
    volumes:
      - .:/app
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python manage.py runserver 0.0.0.0:8000'
    depends_on:
      - db